CrmApp/Controllers/TaskCategoryController.cs
using CrmApp.Models;
using CrmApp.ViewModel.WorkViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CrmApp.Controllers
{
    //[Authorize]
    public class TaskCategoryController : Controller
    {
        private readonly CrmAppDbContext _context;

        public TaskCategoryController(CrmAppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> List()
        {
            var categoriList = await _context.Categories.ToListAsync();

            return View(categoriList);
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(CategoryCreateViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            Categories categories = new Categories();

            categories.CategoryName = model.CategoryName;
            await _context.AddAsync(categories);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(TaskCategoryController.List));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            var categoryEditViewModel = new CategoryEditViewModel()
            {
                Id = category.Id,
                CategoryName = category.CategoryName

            };

            return View(categoryEditViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var categories = await _context.Categories.FindAsync(model.Id);
            categories.CategoryName=model.CategoryName;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(TaskCategoryController.List));

        }


        public IActionResult Delete(int id)
        {
            var category =  _context.Categories.Find(id);
            var categoryEditViewModel = new CategoryEditViewModel()
            {
                Id = category.Id,
                CategoryName = category.CategoryName

            };

            return View(categoryEditViewModel);
        }


        [HttpPost]
        public  IActionResult Delete(CategoryEditViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            var categories =  _context.Categories.Find(model.Id);
            categories.CategoryName = model.CategoryName;
            _context.Remove(categories);
            _context.SaveChanges();

            return View();


        }
        
    }
}

CrmApp/Views/TaskCategory/Create.cshtml
@model CrmApp.Models.Categories

@{
    ViewData["Title"] = "Create";
}

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <h5>Kategori Oluştur</h5>
                    <hr />

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="CategoryName" class="control-label">Kategori</label>
                        <input asp-for="CategoryName" class="form-control" />
                        <span asp-validation-for="CategoryName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Oluştur" class="btn btn-secondary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a class="btn btn-info" asp-action="List">Listeye Geri Dön</a>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CrmApp/Views/TaskCategory/Delete.cshtml
@model CategoryEditViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Categories</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="list">Back to List</a>
    </form>
</div>

CrmApp/Views/TaskCategory/Edit.cshtml
@model CategoryEditViewModel

@{
    ViewData["Title"] = "Edit";
}


<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <h4>Kategori Oluştur</h4>
                <hr />
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="CategoryName" class="control-label">Kategori Adı</label>
                        <input asp-for="CategoryName" class="form-control" />
                        <span asp-validation-for="CategoryName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Düzelt" class="btn btn-secondary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="List" class="btn btn-info">Kategori Listesine Geri Dön</a>
        </div>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
        }

CrmApp/Views/TaskCategory/List.cshtml
@model IEnumerable<CrmApp.Models.Categories>

@{
    ViewData["Title"] = "List";
}

<div class="card">
    <div class="card-body">
        <h5>Kategori Listesi</h5>
        <hr />
        <div class="row">
            <div class="col-md-4">                               
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Kategori Adı
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CategoryName)
                                </td>
                                <td>
                                    <a class="btn btn-warning" asp-controller="TaskCategory" asp-action="Edit" asp-route-id="@item.Id">Düzenle</a> |
@*                                    <a class="btn btn-gray" asp-action="Details" asp-route-id="@item.Id">Detay</a> |
*@@*                                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Sil</a>
*@                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div>
        <a asp-action="Create" class="btn btn-secondary my-4">Yeni Kategori Oluştur</a>
        </div>       
    </div>
</div>