CrmApp/Models/Works.cs
using CrmApp.Models.Entities;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrmApp.Models
{
    public class Works
    {

        public int Id { get; set; }

        [StringLength(50)]
        public string Title { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        [StringLength(250)]
        public string? FinishedDescription { get; set; }

        [StringLength(50)]
        public string Status { get; set; }

        public byte Progress { get; set; }


        [StringLength(50)]
        public string WhoIsCreate { get; set; }

        public DateTime Create { get; set; }

        public DateTime Update { get; set; }

        public DateTime DeadLine { get; set; }

        public DateTime Finished { get; set; }

        public int Departman { get; set; }

        public int WorkOpenDepartman { get; set; }


        [StringLength(25)]
        public string WorkOrderNumber { get; set; }


        [StringLength(50)]
        public string? ApprovedNote { get; set; }

        public int AppUserId { get; set; }
        public AppUser AppUser { get; set; }

        public int VarlikCategoriesId { get; set; }
        public VarlikCategories VarlikCategories { get; set; }





    }
}

CrmApp/Controllers/WorksController.cs
using CrmApp.Models;
using CrmApp.Models.Entities;
using CrmApp.ViewModel.RoleViewModels;
using CrmApp.ViewModel.UserViewModels;
using CrmApp.ViewModel.WorkViewModels;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;

namespace CrmApp.Controllers
{
    public class WorksController : Controller
    {

        private readonly SignInManager<AppUser> _SignInManager;
        private readonly UserManager<AppUser> _UserManager;
        private readonly CrmAppDbContext _context;

        public WorksController(CrmAppDbContext context, SignInManager<AppUser> signInManager = null, UserManager<AppUser> userManager = null)
        {
            _context = context;
            _SignInManager = signInManager;
            _UserManager = userManager;
        }


        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> Create()
        {
            var categoryVarlik = await _context.Varlikcategories.Include(v => v.Categories).Include(v => v.Varlik).ToListAsync();


            ViewData["VarlikCategoriesId"] = new SelectList(categoryVarlik, "Id", "VarlikCategoriesName");


            //ViewData["CategoryId"] = new SelectList(_context.VarlikCategories, "Id", "CategoryName");
            ViewData["DepartmanId"] = new SelectList(_context.Departman, "Id", "DepartmanName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(WorksCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["message"] = "Bir hata oluştu";
                return View();
            }
            var categoryVarlik = await _context.Varlikcategories.Include(v => v.Categories).Include(v => v.Varlik).ToListAsync();


            ViewData["VarlikCategoriesId"] = new SelectList(categoryVarlik, "Id", "VarlikCategoriesName");

            //ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "NameSurName");
            //ViewData["CategoryId"] = new SelectList(_context.VarlikCategories, "Id", "CategoryName");
            ViewData["DepartmanId"] = new SelectList(_context.Departman, "Id", "DepartmanName");

            DateTime systemClock = DateTime.Now;
            DateTime controlClock = systemClock.AddMinutes(30);

            if (controlClock >= model.DeadLine)
            {
                TempData["timeMessage"] = "Talep ettiğiniz tarih sistem saatinden minimum 30 dk yukarıda olmak zorundadır!";
                return View();
            }



            string numberUp = "";

            DateTime thisYear = DateTime.Now;
            string years = Convert.ToString(thisYear.Year % 100);


            var currentWorks = await _context.Works.OrderByDescending(x => x.WorkOrderNumber).FirstOrDefaultAsync();


            if (currentWorks != null)
            {
                string number = currentWorks.WorkOrderNumber.Substring(currentWorks.WorkOrderNumber.Length - 3);
                int numberIntl = Convert.ToInt32(number) + 1;
                string numberString = Convert.ToString(numberIntl);

                if (numberString.Length <= 1)
                {
                    numberUp = years + "-" + "000" + (Convert.ToString(numberString));

                }
                else if (numberString.Length <= 2)
                {
                    numberUp = years + "-" + "00" + (Convert.ToString(numberString));

                }
                else if (numberString.Length <= 3)
                {
                    numberUp = years + "-" + "0" + (Convert.ToString(numberString));

                }

            }
            else
            {
                numberUp = years + "-" + "0001";
            }

            var user = await _UserManager.FindByNameAsync(User.Identity.Name);

            var result = new Works()
            {
                Title = model.Title,
                Description = model.Description,
                Status = model.Status,
                Progress = model.Progress,
                WhoIsCreate = user.NameSurName,
                Create = model.Create,
                Update = model.Update,
                DeadLine = model.DeadLine,
                Finished = model.Finished,
                AppUserId = 1,
                VarlikCategoriesId = model.VarlikCategoriesId,
                Departman = model.Departman,
                WorkOpenDepartman = user.DepartmanId,
                WorkOrderNumber = numberUp

            };

            await _context.AddAsync(result);
            await _context.SaveChangesAsync();
            TempData["message"] = "İş ataması başarılı. Yeni kayıt açabilirsiniz!";

            return RedirectToAction(nameof(WorksController.Create));

        }

        public async Task<IActionResult> WorksAppRovedList(int Id)
        {
            var worksList = await _context.Works.ToListAsync();

            var userControl = await _UserManager.FindByNameAsync(User.Identity.Name);




            var worksListViewModel = worksList.Where(x => x.Departman == (userControl.DepartmanId) & x.Status == "beklemede").Select(x => new WorksApprovedList()
            {
                Id = x.Id,
                Title = x.Title,
                Create = x.Create,
                DeadLine = x.DeadLine,
                WhoIsCreate = x.WhoIsCreate,
                Status = x.Status,
                WorkOrderNumber = x.WorkOrderNumber,

            }).OrderByDescending(x=> x.Id).ToList();
            return View(worksListViewModel);
        }



        public async Task<IActionResult> WorkStatusApprovalDetail(int Id)
        {
            var userControl = await _UserManager.FindByNameAsync(User.Identity.Name);

            var bilgiIslemKullanicilari = _context.Users
               .Where(u => u.DepartmanId == userControl.DepartmanId && u.Status == "onaylandı")
               .Select(u => new { Id = u.Id, NameSurName = u.NameSurName })
               .ToList();

            // SelectList'e eklerken kullanabilirsiniz
            ViewData["AppUserId"] = new SelectList(bilgiIslemKullanicilari, "Id", "NameSurName");


            var worksDetails = await _context.Works.Where(x => x.Id == Id).FirstOrDefaultAsync();
            var user = await _context.Users.Where(x => x.Id == worksDetails.AppUserId).FirstOrDefaultAsync();
            var category = await _context.Varlikcategories.Where(x => x.Id == worksDetails.VarlikCategoriesId).FirstOrDefaultAsync();


            var details = new DetailWork()
            {
                Id = worksDetails.Id,
                Title = worksDetails.Title,
                Description = worksDetails.Description,
                WhoIsCreate = worksDetails.WhoIsCreate,
                Status = worksDetails.Status,
                Progress = worksDetails.Progress,
                Create = worksDetails.Create,
                Update = worksDetails.Update,
                DeadLine = worksDetails.DeadLine,
                Finished = worksDetails.Finished,
                AppUserId = user.Id,
                AppUser = user.UserName,
                VarlikCategories = category.VarlikCategoriesName,
                WorkOrderNumber = worksDetails.WorkOrderNumber,
                ApprovedNote = worksDetails.ApprovedNote

            };
            return View(details);
        }

        [HttpPost]
        public async Task<IActionResult> WorkStatusApprovalDetail(int Id, DetailWork model)
        {
            var userControl = await _UserManager.FindByNameAsync(User.Identity.Name);

            var bilgiIslemKullanicilari = _context.Users
               .Where(u => u.DepartmanId == userControl.DepartmanId && u.Status == "onaylandı")
               .Select(u => new { Id = u.Id, NameSurName = u.NameSurName })
               .ToList();

            ViewData["AppUserId"] = new SelectList(bilgiIslemKullanicilari, "Id", "NameSurName");


            var worksDetails = await _context.Works.Where(x => x.Id == Id).FirstOrDefaultAsync();
            var user = await _context.Users.Where(x => x.Id == worksDetails.AppUserId).FirstOrDefaultAsync();
            var category = await _context.Categories.Where(x => x.Id == worksDetails.VarlikCategoriesId).FirstOrDefaultAsync();


            if (worksDetails != null)
            {
                worksDetails.Status = "onaylandı";
                worksDetails.AppUserId = model.AppUserId;
                worksDetails.ApprovedNote = model.ApprovedNote;
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(WorksController.WorksAppRovedList));
        }




        public async Task<IActionResult> DetailWork(int Id)
        {
            var worksDetails = await _context.Works.Where(x => x.Id == Id).FirstOrDefaultAsync();
            var user = await _context.Users.Where(x => x.Id == worksDetails.AppUserId).FirstOrDefaultAsync();
            var category = await _context.Varlikcategories.Where(x => x.Id == worksDetails.VarlikCategoriesId).FirstOrDefaultAsync();


            var details = new DetailWork()
            {
                Id = worksDetails.Id,
                Title = worksDetails.Title,
                Description = worksDetails.Description,
                WhoIsCreate = worksDetails.WhoIsCreate,
                Status = worksDetails.Status,
                Progress = worksDetails.Progress,
                Create = worksDetails.Create,
                Update = worksDetails.Update,
                DeadLine = worksDetails.DeadLine,
                Finished = worksDetails.Finished,
                AppUser = user.UserName,

CrmApp/Views/Works/DetailWork.cshtml
@model DetailWork
@section Scripts
    {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

<div class="card card-bordered card-preview">
    <div class="card-inner">
        <div id="DataTables_Table_3_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row justify-between g-2 with-export">
                <div class="card-inner">
                    <div class="preview-block">
                        <h4 class="my-4">İşinizin Detayı</h4>
                        <div class="row gy-4">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-control-wrap">
                                        <div class="alert alert-pro alert-dark">
                                            <div class="alert-text">
                                                <h6>İş No</h6>
                                                <p>@Model.WorkOrderNumber </p>
                                                <h6>İşi Açan Kişi</h6>
                                                <p>@Model.WhoIsCreate </p>
                                                <h6>İşin Kategorisi</h6>
                                                <p>@Model.VarlikCategories </p>
                                                <h6>İşin Konusu</h6>
                                                <p>@Model.Title </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="alert alert-pro alert-danger">
                                        <div class="alert-text">
                                            <h6>İşin Açıldığı Tarih</h6>
                                            <p>@Model.Create </p>
                                            <h6>Talep Edilen Tarihi</h6>
                                            <p>@Model.DeadLine </p>
                                            <h6>Onaylayan Notu</h6>
                                            <p>@Model.ApprovedNote</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="alert alert-pro alert-info">
                                        <div class="alert-text">
                                            <h6>İşin Açıklaması</h6>
                                            <p>@Model.Description</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <form asp-action="WorkStatusFinished" asp-controller="Works" asp-route-id="@Model.Id" method="post">
                                <div class="col-sm-12 my-3">
                                    <div class="form-group">
                                        <div class="alert alert-pro alert-warning">
                                            <div class="alert-text">
                                                <label class="form-label" for="default-textarea"><h5>Çözüm Detayları</h5></label>
                                                @if (Model.Status == "bitti")
                                                {
                                                    <div class="input-group flex-nowrap">
                                                        <p>@Model.FinishedDescription</p>
                                                    </div>
                                                }
                                                else
                                                {
                                                    <div class="input-group flex-nowrap">
                                                        <input asp-for="FinishedDescription" type="text" class="form-control form-control-lg" id="name" placeholder="Çözüm notunuzu bu alana yazınız">
                                                    </div>
                                                    <span class="text-danger" asp-validation-for="FinishedDescription"></span>
                                                }

                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-3 my-4">
                                    @if (Model.Status == "başlandı")
                                    {
                                        <button type="submit" class="btn btn-danger">İşi Tamamla</button>

                                    }
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CrmApp/Views/Works/MyWorks.cshtml
@model List<WorksApprovedList>

@{
    ViewData["Title"] = "MyWorks";
}


<div class="card card-bordered card-preview">
    <div class="card-inner">
        <div id="DataTables_Table_3_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row justify-between g-2 with-export">
                <div class="col-7 col-sm-4 text-start">
                    <div id="DataTables_Table_3_filter" class="dataTables_filter">
                        <label>
                            <input type="search" id="searchInput" class="form-control form-control-sm" placeholder="Ara" aria-controls="DataTables_Table_3">
                        </label>
                    </div>
                </div>
                <div class="col-5 col-sm-8 text-end">
                    <div class="datatable-filter">
                        <div class="d-flex justify-content-end g-2">
                            <div class="dt-export-buttons d-flex align-center">
                                <div class="dt-export-title d-none d-md-inline-block">Dışa Aktar</div>
                                <div class="dt-buttons btn-group flex-wrap">
                                    <button class="btn btn-secondary buttons-copy buttons-html5" tabindex="0" aria-controls="DataTables_Table_3" type="button"><span>Copy</span></button>
                                    <button class="btn btn-secondary buttons-excel buttons-html5" tabindex="0" aria-controls="DataTables_Table_3" type="button" id="exportToExcel"><span>Excel</span></button>
                                    <button class="btn btn-secondary buttons-csv buttons-html5" tabindex="0" aria-controls="DataTables_Table_3" type="button"><span>CSV</span></button>
                                    <button class="btn btn-secondary buttons-pdf buttons-html5" tabindex="0" aria-controls="DataTables_Table_3" type="button"><span>PDF</span></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><div class="datatable-wrap my-3">
                <table class="nowrap table dataTable no-footer dtr-inline" data-export-title="Dışa Aktar" id="DataTables_Table_3" aria-describedby="DataTables_Table_3_info">
                    <thead>
                        <tr>
                            <th class="sorting sorting_asc" tabindex="0" aria-controls="DataTables_Table_3" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending">İşi Açan</th>
                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_3" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending">İş Emri Numarası</th>
                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_3" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending">İşin Konusu</th>

                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_3" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending">İşin Açılma Tarihi</th>
                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_3" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending">İşin İstenen Bitiş Tarihi</th>
                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_3" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending">Durumu</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="odd">
                                <td class="dtr-control sorting_1" tabindex="0">@item.WhoIsCreate</td>
                                <td>@item.WorkOrderNumber</td>
                                <td>@item.Title</td>
                                <td>@item.Create</td>
                                <td>@item.DeadLine</td>
                                <td>@item.Status</td>
                                <td>
                                    <form asp-action="WorksStatusStarted" asp-controller="Works" asp-route-id="@item.Id" method="post">
                                        @if (item.Status=="onaylandı")
                                        {
                                            <button type="submit" class="btn btn-success">Başla</button>

                                        }
                                    </form>                                    
                                </td>
                                <td>
                                    <a class="btn btn-secondary" asp-action="DetailWork" asp-route-id="@item.Id">Detay</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>





<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.5/xlsx.full.min.js"></script>


<script>
    $(document).ready(function () {
        $("#searchInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#DataTables_Table_3 tbody tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

<script>
    $(document).ready(function () {
        $("#searchInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#DataTables_Table_3 tbody tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });

        $("#exportToExcel").on("click", function () {
            exportTableToExcel();
        });

        function exportTableToExcel() {
            var htmltable = document.getElementById('DataTables_Table_3');
            var html = htmltable.outerHTML;

            var blob = new Blob([html], {
                type: 'application/vnd.officedocument.spreadsheetml.sheet'
            });
            var a = document.createElement('a');
            a.href = window.URL.createObjectURL(blob);
            a.download = 'is_listesi.xls';
            a.style.display = 'none';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
        }
    });
</script>

CrmApp/Views/Works/WorkStatusApprovalDetail.cshtml
@model DetailWork
@section Scripts
    {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

<div class="card card-bordered card-preview">
    <div class="card-inner">
        <div id="DataTables_Table_3_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row justify-between g-2 with-export">
                <div class="card-inner">
                    <div class="preview-block">
                        <h4 class="my-4">İşinizin Detayı</h4>
                        <div class="row gy-4">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-control-wrap">
                                        <div class="alert alert-pro alert-dark">
                                            <div class="alert-text">
                                                <h6>İş Emri Numarası</h6>
                                                <p>@Model.WorkOrderNumber </p>

                                                <h6>İşin Konusu</h6>
                                                <p>@Model.Title </p>

                                                <h6>İşin Açıklaması</h6>
                                                <p>@Model.Description</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-control-wrap">
                                        <div class="alert alert-pro alert-dark">
                                            <div class="alert-text">
                                                <h6>İşi Açan Kişi</h6>
                                                <p>@Model.WhoIsCreate </p>

                                                <h6>İşin Kategorisi</h6>
                                                <p>@Model.VarlikCategories </p>
                                            </div>
                                        </div>
                                        <div class="alert alert-pro alert-info">
                                            <div class="alert-text">
                                                <h6>İşin Açıldığı Tarih</h6>
                                                <p>@Model.Create </p>
                                                <h6>Talep Edilen Tarih</h6>
                                                <p>@Model.DeadLine </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <form asp-controller="Works" asp-action="WorkStatusApprovalDetail" asp-route-id="@Model.Id" method="post">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="alert alert-pro alert-danger">
                                            <div class="alert-text">
                                                <h6>İş Ataması</h6>
                                                <select asp-for="AppUserId" class="form-select js-select2" data-search="on" asp-items="ViewBag.AppUserId"></select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="alert alert-pro alert-danger">
                                            <div class="alert-text">
                                                <h6>Onaylayan Notu</h6>
                                                <div class="input-group flex-nowrap">
                                                    <input asp-for="ApprovedNote" class="form-control" placeholder="Lütfen notunuzu bu alana giriniz. (Maksimum 50 karakter)" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                @if (Model.Status == "beklemede")
                                {

                                    <div class="col-sm-3 my-4">
                                        <button type="submit" class="btn btn-warning">Onayla</button>
                                    </div>
                                }
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>