CrmApp/Models/Varlik.cs
using CrmApp.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace CrmApp.Models
{
    public class Varlik
    {
        public int Id { get; set; }

        [StringLength(50)]
        public string VarlikName { get; set; }
        public ICollection<VarlikCategories> VarlikCategories { get; set; } = new HashSet<VarlikCategories>();

    }
}

CrmApp/Controllers/VarlikCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrmApp.Models;

namespace CrmApp.Controllers
{
    public class VarlikCategoriesController : Controller
    {
        private readonly CrmAppDbContext _context;

        public VarlikCategoriesController(CrmAppDbContext context)
        {
            _context = context;
        }

        // GET: VarlikCategories
        public async Task<IActionResult> Index()
        {
            var crmAppDbContext = _context.Varlikcategories.Include(v => v.Categories).Include(v => v.Varlik);
            return View(await crmAppDbContext.ToListAsync());
        }

        // GET: VarlikCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Varlikcategories == null)
            {
                return NotFound();
            }

            var VarlikCategories = await _context.Varlikcategories
                .Include(v => v.Categories)
                .Include(v => v.Varlik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (VarlikCategories == null)
            {
                return NotFound();
            }

            return View(VarlikCategories);
        }

        // GET: VarlikCategories/Create
        public IActionResult Create()
        {
            ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "CategoryName");
            ViewData["VarlikId"] = new SelectList(_context.Varliks, "Id", "VarlikName");
            return View();
        }

        // POST: VarlikCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VarlikCategories model)
        {
            var varlik = await _context.Varliks.FindAsync(model.VarlikId);
            var category = await _context.Categories.FindAsync(model.CategoriesId);

            var varlikCategories = new VarlikCategories()
            {
                VarlikId = model.VarlikId,
                CategoriesId = model.CategoriesId,
                VarlikCategoriesName = varlik.VarlikName + "-" + category.CategoryName
            };

            _context.Add(varlikCategories);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            //ViewData["CategoriesId"] = new SelectList(_context.VarlikCategories, "Id", "CategoryName", VarlikCategories.CategoriesId);
            //ViewData["VarlikId"] = new SelectList(_context.Varliks, "Id", "VarlikName", VarlikCategories.VarlikId);
            //return View(VarlikCategories);
        }

        // GET: VarlikCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Varlikcategories == null)
            {
                return NotFound();
            }

            var VarlikCategories = await _context.Varlikcategories.FindAsync(id);
            if (VarlikCategories == null)
            {
                return NotFound();
            }
            ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "CategoryName", VarlikCategories.CategoriesId);
            ViewData["VarlikId"] = new SelectList(_context.Varliks, "Id", "VarlikName", VarlikCategories.VarlikId);
            return View(VarlikCategories);
        }

        // POST: VarlikCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,VarlikId,CategoriesId")] VarlikCategories model)
        {


            var varlik = await _context.Varliks.FindAsync(model.VarlikId);
            var category = await _context.Categories.FindAsync(model.CategoriesId);
            var findVarlikCategory = await _context.Varlikcategories.Where(x => x.Id == id).FirstOrDefaultAsync();


            if (findVarlikCategory != null)
            {
                findVarlikCategory.VarlikId = model.VarlikId;
                findVarlikCategory.CategoriesId = model.CategoriesId;
                findVarlikCategory.VarlikCategoriesName = varlik.VarlikName + "-" + category.CategoryName;
                await _context.SaveChangesAsync();

            }

            return RedirectToAction(nameof(Index));





            //if (id != VarlikCategories.Id)
            //{
            //    return NotFound();
            //}

            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        _context.Update(VarlikCategories);
            //        await _context.SaveChangesAsync();
            //    }
            //    catch (DbUpdateConcurrencyException)
            //    {
            //        if (!VarlikCategoriesExists(VarlikCategories.Id))
            //        {
            //            return NotFound();
            //        }
            //        else
            //        {
            //            throw;
            //        }
            //    }
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "CategoryName", VarlikCategories.CategoriesId);
            //ViewData["VarlikId"] = new SelectList(_context.Varliks, "Id", "VarlikName", VarlikCategories.VarlikId);
            //return View(VarlikCategories);
        }

        // GET: VarlikCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Varlikcategories == null)
            {
                return NotFound();
            }

            var VarlikCategories = await _context.Varlikcategories
                .Include(v => v.Categories)
                .Include(v => v.Varlik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (VarlikCategories == null)
            {
                return NotFound();
            }

            return View(VarlikCategories);
        }

        // POST: VarlikCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Varlikcategories == null)
            {
                return Problem("Entity set 'CrmAppDbContext.Varlikcategories'  is null.");
            }
            var VarlikCategories = await _context.Varlikcategories.FindAsync(id);
            if (VarlikCategories != null)
            {
                _context.Varlikcategories.Remove(VarlikCategories);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VarlikCategoriesExists(int id)
        {
            return (_context.Varlikcategories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CrmApp/Controllers/VarliksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrmApp.Models;

namespace CrmApp.Controllers
{
    public class VarliksController : Controller
    {
        private readonly CrmAppDbContext _context;

        public VarliksController(CrmAppDbContext context)
        {
            _context = context;
        }

        // GET: Varliks
        public async Task<IActionResult> Index()
        {
              return _context.Varliks != null ? 
                          View(await _context.Varliks.ToListAsync()) :
                          Problem("Entity set 'CrmAppDbContext.Varliks'  is null.");
        }

        // GET: Varliks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Varliks == null)
            {
                return NotFound();
            }

            var varlik = await _context.Varliks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (varlik == null)
            {
                return NotFound();
            }

            return View(varlik);
        }

        // GET: Varliks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Varliks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,VarlikName")] Varlik varlik)
        {
            if (ModelState.IsValid)
            {
                _context.Add(varlik);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(varlik);
        }

        // GET: Varliks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Varliks == null)
            {
                return NotFound();
            }

            var varlik = await _context.Varliks.FindAsync(id);
            if (varlik == null)
            {
                return NotFound();
            }
            return View(varlik);
        }

        // POST: Varliks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,VarlikName")] Varlik varlik)
        {
            if (id != varlik.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(varlik);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VarlikExists(varlik.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(varlik);
        }

        // GET: Varliks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Varliks == null)
            {
                return NotFound();
            }

            var varlik = await _context.Varliks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (varlik == null)
            {
                return NotFound();
            }

            return View(varlik);
        }

        // POST: Varliks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Varliks == null)
            {
                return Problem("Entity set 'CrmAppDbContext.Varliks'  is null.");
            }
            var varlik = await _context.Varliks.FindAsync(id);
            if (varlik != null)
            {
                _context.Varliks.Remove(varlik);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VarlikExists(int id)
        {
          return (_context.Varliks?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CrmApp/Views/Varliks/Create.cshtml
@model CrmApp.Models.Varlik

@{
    ViewData["Title"] = "Create";
}

<div class="card">
    <div class="card-body">
        <h4>Varlik Oluştur</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="VarlikName" class="control-label">Varlık Adı</label>
                        <input asp-for="VarlikName" class="form-control" />
                        <span asp-validation-for="VarlikName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Oluştur" class="btn btn-secondary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a class="btn btn-info" asp-action="Index">Varlık Listesine Dön</a>
        </div>
    </div>

</div>

CrmApp/Views/Varliks/Delete.cshtml
@model CrmApp.Models.Varlik

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Varlik</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VarlikName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VarlikName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CrmApp/Views/Varliks/Details.cshtml
@model CrmApp.Models.Varlik

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Varlik</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VarlikName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VarlikName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CrmApp/Views/Varliks/Edit.cshtml
@model CrmApp.Models.Varlik

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Varlik</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="VarlikName" class="control-label"></label>
                <input asp-for="VarlikName" class="form-control" />
                <span asp-validation-for="VarlikName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CrmApp/Views/Varliks/Index.cshtml
@model IEnumerable<CrmApp.Models.Varlik>

@{
    ViewData["Title"] = "Index";
}

<div class="card">
    <div class="card-body">
        <h4>Varlık Listesi</h4>
        <hr />
        <p>
            <a class="btn btn-secondary" asp-action="Create">Yeni Oluştur New</a>
        </p>
        <p><a class="btn btn-primary" asp-controller="VarlikCategories" asp-action="Create"> Kategori Ata</a></p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Varlık Adı
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.VarlikName)
                        </td>
                        <td>
                            <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Düzelt</a> |
                           @* <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>